### ISSUE TITLE
runtime detection for avaliable libtcti-tabrmd.so

### ISSUE THREAD

**Issue by liuqun** [irtimmer/tpm2-pk11#13]
"libtcti-xxx.so" may be available on current system which builds "libtpm2-pk11", but not available on many new systems that uses "/dev/tpmrm0" as kernel-space TPM resource manager. So currently I have to build two "libtpm2-pk11.so"  RPM packages, one of which compiled with TCTI_TABRMD_ENABLED while the other one not.

Linking against "libtcti-tabrmd.so" at compile-time is simpler for an demo project, but less flexible for final products.

Maybe it's better to implement a probe function "tcti_probe()" so that we may load "libtcti-tabrmd.so" as an dynamic-linked lib at run-time.

**Comment by irtimmer** [comment]
Requiring _libtcti-tabrmd.so_ to be available at runtime doesn't seem to me as a very big barrier. It isn't even required that the _tpm2-abrmd_ is running.
