### ISSUE TITLE
No fail-safe config if ~/.tpm2/config is not found or not readable

### ISSUE THREAD

**Issue by liuqun** [irtimmer/tpm2-pk11#14]
For example, when "~/.tpm2/config" is removed ,ssh-keygen will only complain to me that "C_Initialize failed: 5" (CKR_GENERAL_ERROR).

```
pi@raspberry:~$ rm --interactive -r .tpm2
rm: descend into directory '.tpm2'? y
rm: remove regular file '.tpm2/config'? y
rm: remove directory '.tpm2'? y
```
Then the following error message seems quiet confusing to me:
```
pi@raspberry:~$ ssh-keygen -D /src/tpm2-pk11/libtpm2-pk11.so
C_Initialize failed: 5
cannot read public key from pkcs11
```

https://github.com/irtimmer/tpm2-pk11/blob/a34772a2ea68bf9bcecfe7155e1093e300ad04da/src/pk11.c#L224-L231

https://github.com/irtimmer/tpm2-pk11/blob/a34772a2ea68bf9bcecfe7155e1093e300ad04da/src/config.c#L34-L38

https://github.com/irtimmer/tpm2-pk11/blob/a34772a2ea68bf9bcecfe7155e1093e300ad04da/src/pk11.c#L36

If ~/.tpm2/config is not found or not readable, there should be a fail-back safe built-in configuration to load, for example using fmemopen() to load a string as an "fd":
```
int config_load(char* filename, struct config *config) {
  FILE* fd = fopen(filename, "r");
  
  if (fd == NULL) {
    static char failback[] =
            "type device\n"
            "hostname localhost\n"
            "port 2321\n"
            "device /dev/tpm0\n"
            "sign-using-encrypt true\n";
    fd = fmemopen(failback, sizeof(failback), "r");
  }
```

We may also create a log file (e.g. "/var/log/tpm2-pk11.log") for libtpm2-pk11.so, so that we will be able to record that the error msg "C_Initialize failed" is caused by "failed to open ~/.tpm2/config: no such file".

**Comment by irtimmer** [comment]
The problematic error message is mostly the fault of the PKCS#11 as we can't provide clear error messages but only error codes. It's not an easy piece of software to use and therefore I expect the targeted audience doesn't have difficulties with creating a configuration file. Because of all the different connection possibilities I don't even know which I should set as default.
