### ISSUE TITLE
Arch AUR

### ISSUE THREAD

**Issue by krisclarkdev** [irtimmer/tpm2-pk11#16]
Hey man, I made a PKGBUILD for this project and submitted it to AUR last night.  Let me know if I need to change anything to give you credit or whatever on it

https://aur.archlinux.org/packages/tpm2-pk11

**Comment by sum01** [comment]
```
cd "$srcdir/$pkgname"
cd build
sudo make install
```
should be
```
cd "$srcdir/$pkgname/build"
make DESTDIR="$pkgdir" install
```
You generally don't use su/sudo in PKGBUILD's, as it's a fakeroot environment.

Also, non-custom licenses can be found in `/usr/share/licenses/common`. The correct license would be `license=('LGPL2.1')`

**Comment by irtimmer** [comment]
The main reason I created a separate AUR package was the usage of your forked git repository in the PKGBUILD. You can remove your package if you want. In that case I probably will recreate the tpm2-pk11 package as soon as a stable release is ready.
