### ISSUE TITLE
Add changelog and new release 

### ISSUE THREAD

**Issue by szlin** [irtimmer/tpm2-pk11#19]
Hi,

I am a debian developer, and I am going to package your utility into Debian archive. 
Could you add changelog and make a new release with version 1.0(perhaps)?

Thanks.

SZ

**Comment by liuqun** [comment]
Fork this project and upload your own release tag. Create a time-based git tag instead of release number. It will be more friendly to developers than a formal version number such as "1.x" / "2.x".
For example:
tag **git20171120** and deb **libtpm2-pk11_git20171120-1_amd64.deb**

**Comment by szlin** [comment]
@liuqun Thanks for your reply. 
You suggestion can meet the demand by all means; however, "Upstream first" policy is important for open source, and thus "proprietary version" should be avoided unless special cases happened, e.g., upstream author is too busy for maintaining project.

**Comment by irtimmer** [comment]
If have no plans yet to release a first version. As before I release a version, I want at least to have implemented password support and added the functionality to import keys.

**Comment by szlin** [comment]
@irtimmer

**Comment by liuqun** [comment]
@szlin , I hope to merge your works into upstream git repo. Can you push your git repo onto github.com and create one pull-request to other developer?

I see your changes has been uploaded to debian.org:
https://anonscm.debian.org/git/collab-maint/tpm2-pk11.git

**Comment by szlin** [comment]
We follow "upstream first" policy; hence the changes in Debian will be forwarded to here as a PR.

**Comment by szlin** [comment]
@liuqun Since tpm2-pk11 depends on tpm2-tss, I am co-working with the package maintainer of tpm2-tss for upgrading task.

**Comment by szlin** [comment]
@liuqun The new version of tpm2-pk11 has been uploaded after the tpm2-abrmd got accepted into Debian archive.
