### ISSUE TITLE
Config options in README are outdated

### ISSUE THREAD

**Issue by rtkypoeluev** [irtimmer/tpm2-pk11#2]
Can you please check the section about config file settings in README? I don't think the code supports it now. Also, I thought the second line below should have had ">>" instead of ">", to have both lines in the config file.

```
echo key ~/tpm2/key.pub > ~/.tpm2/config
echo "key_handle 0x81010010" > ~/.tpm2/config
```

Thanks

**Comment by irtimmer** [comment]
Fixed with commit 21cb46f5491e99d4175aa1fc88dde3224e3dbc82
