### ISSUE TITLE
Dependency pakages needed.

### ISSUE THREAD

**Issue by tuanbs232** [irtimmer/tpm2-pk11#22]
How can I install needed packages for pkg-config: p11-kit-1, sapi, ...
I'm new in CMake base project.
Thanks,

**Comment by liuqun** [comment]
**P11-KIT** C/C++ headers

- Ubuntu / Debian
```
sudo apt-get install libp11-kit-dev
```

- RedHat / Fedora / CentOS
```
 su
password: *******

 yum install p11-kit-devel
```

**Comment by tuanbs232** [comment]
Thanks for your reply, I'll try it as soon as

**Comment by liuqun** [comment]
**libsapi0** C/C++ headers

On Debain / Ubuntu, the official libsapi 0.97 and 1.0 version is outdated.

https://github.com/intel/tpm2-tool/master/.travis.yaml shows me howto build tpm2-tss and tpm2-abrmd

```
git clone https://github.com/01org/TPM2.0-TSS.git
pushd TPM2.0-TSS
wget http://ftpmirror.gnu.org/autoconf-archive/autoconf-archive-2017.09.28.tar.xz
tar xJf autoconf-archive-2017.09.28.tar.xz
cp autoconf-archive-2017.09.28/m4/ax_code_coverage.m4 m4/

nproc=4
./bootstrap && ./configure && make -j$(nproc)
sudo make install
popd
```

**Comment by liuqun** [comment]
tpm2-abrmd is no longer required since Pull Request "https://github.com/irtimmer/tpm2-pk11/pull/12 Make dependent TCTI types optional"

**Comment by liuqun** [comment]
@tuanbs232  

Since Intel's TPM2.0-TSS was updated to an unstable 2.0-dev branch days ago, please use:
```
git clone --branch=1.x --depth=1 https://github.com/01org/TPM2.0-TSS.git
```

instead of the following command:
```
git clone --depth=1 https://github.com/01org/TPM2.0-TSS.git
```

**Comment by liuqun** [comment]
after copying libsapi.so.* from "$HOME/my-tpm2-tss-installation-dir" into "/usr/local/lib", do
```
sudo ldconfig
```

**Comment by liuqun** [comment]
**tpm2-tools**:

```
git clone https://github.com/intel/tpm2-tools --depth=1 --branch=2.X

pushd tpm2-tools
./bootstrap && ./configure --prefix=$HOME && make -j 4
make install DESTDIR=$HOME/my-tpm2-tss-installation-dir
popd
```

**Comment by tuanbs232** [comment]
Thank you very much! @liuqun 
I think all these steps should include an INSTALL file, that will help a lot for beginners like me.

Best regards,

**Comment by liuqun** [comment]
You may fork irtimmer's tpm2-pk11 project, and then upload your modified INSTALL file.

Happy hacking!

**Comment by liuqun** [comment]
I've create an build script to build libtpm2-pk11, see:
https://github.com/liuqun/tpm2-pk11/commit/d228b03a2aead007105e875b002a4c02b926126f

If you have an Ubuntu 16.04 Virtual Mechine with snapd, you'll be able to build every thing with simply one command:
```
snapcraft
```
