### ISSUE TITLE
How does the end user know if their system is capable of using this?

### ISSUE THREAD

**Issue by rbrito** [irtimmer/tpm2-pk11#25]
The subject essentially says it all: how does the user know that their system supports TPM 2.0, before downloading, compiling, failing etc.?

Are there any rules that one can check?

Thanks,

Rogério.

**Comment by liuqun** [comment]
You'll need the following things:
- A working TPM 2.0 software simulator or hardware /dev/tpm0 kernel device driver
- GCC tool-chain and CMake to compile from source code
- https://github.com/intel/tpm2-tss
- https://github.com/intel/tpm2-abrmd
- https://github.com/intel/tpm2-tools

**Comment by irtimmer** [comment]
You can run `dmesg | grep tpm -i` to check if your system has a TPM 2 module, which in my case shows:
`ACPI: TPM2 0x0000000067F597C0 000034 (v03        Tpm2Tabl 00000001 AMI  00000000)`
`tpm_tis MSFT0101:00: 2.0 TPM (device-id 0xFE, rev-id 4)`

**Comment by rbrito** [comment]
Thanks a lot, @irtimmer.
