### ISSUE TITLE
Feature request: Backward compatibility to build against the 1.x stable branch of tpm2-tss 

### ISSUE THREAD

**Issue by liuqun** [irtimmer/tpm2-pk11#27]
Suggestion:

- Don't use anything with a prefix of "TPM_" or "TPM2_" directly!
We should wrap every "TPM2_" things into our own product's header file such as "tpm2-wrapper.h" or "tpm.h", so that we will be able to support both 1.x and 2.0.0-dev branch of Intel's TPM 2.0 implementation.

We should NEVER force our client to update their TSS version to the unstable 2.0.0-dev branch before a beta release of 2.0.0 branch is available.

**Comment by irtimmer** [comment]
A client is NEVER forced and I expect most clients will use a older version of the software as they already use older library versions. As I can only install a single version at a time I develop mostly to the most recent version and I have no benefit for myself by supporting older library versions. But if someone would create a compatibility layer for the 1.x, which requires minimal changes to the current code so it could easily be removed when no longer needed, I would happily merge it.

**Comment by irtimmer** [comment]
Backward compatibility is now provided with commit 018dc68e0a438ff8e7bb308458dad9ce48e4541f

**Comment by liuqun** [comment]
This compatible layer works for me, thanks very much!
