### ISSUE TITLE
Coding style review: "int fd" or "FILE *fd"?

### ISSUE THREAD

**Issue by liuqun** [irtimmer/tpm2-pk11#31]
The following code is misleading:
https://github.com/irtimmer/tpm2-pk11/blob/9f38c0520a355aefd066c49003d38fbe2be7d99d/src/config.c#L35

It should be either a stream-buffered FILE structure ptr returned from libc `fopen()`:
```
#include <stdio.h>

    FILE *fp = fopen(filename, "r");
```
or a none-buffered file descriptor returned by Unix system call `open()`:
```
#include <fcntl.h>
#include <unistd.h>

    int fd = open(filename, O_RDONLY);
```

Reference to the following Linux manual pages:
- `man 2 open`
- `man 3 fopen`

**Comment by irtimmer** [comment]
Fixed with commit ecadebef103ae4683b2c6fc65d3a01555f13627f
