### ISSUE TITLE
Bug: local variable ret was used before assigned

### ISSUE THREAD

**Issue by liuqun** [irtimmer/tpm2-pk11#4]
https://github.com/irtimmer/tpm2-pk11/blob/f3ebb25aacc79c4360dbfebe49daea4245079338/src/pk11.c#L180-L197

Bug:

In if-else code block, variable **TPM_RC ret** was redefined. This make the top level variable un-assigned before it was used!

On my raspberry Pi, C_Sign() always returns CKR_GENERAL_ERROR=5 even if my TPM 2.0 chip returns TPM_RC_SUCCESS=0

**Comment by irtimmer** [comment]
That doesn't seem right. Maybe I refactored the code after testing or my compile is more forgiving. At least I have merged your patch so it should be fixed for everyone now.
