### ISSUE TITLE
Old log file will be overwirtten at the beginning of each session

### ISSUE THREAD

**Issue by liuqun** [irtimmer/tpm2-pk11#40]
https://github.com/irtimmer/tpm2-pk11/blob/7c6aa346d5d37e5cb1c233cce90b4f5646905fe0/src/pk11.c#L242-L251

https://github.com/irtimmer/tpm2-pk11/blob/31d45ce73d69ee094e3ab58b31a6dfcebde339cd/src/log.c#L30-L40

It seemd that we shoud call `fopen(filename, "a");` to add new lines.

**Comment by irtimmer** [comment]
Issue have been fixed with commit 12c3061eb22dbfc397cd08c4d5b78951a8dae04b
