### ISSUE TITLE
main_session never get closed after C_Finalize()

### ISSUE THREAD

**Issue by liuqun** [irtimmer/tpm2-pk11#44]
https://github.com/irtimmer/tpm2-pk11/blob/f08ab6ab3bbc85f7b199c707416e3e10e6b9e3f4/src/pk11.c#L150-L153

https://github.com/irtimmer/tpm2-pk11/blob/f08ab6ab3bbc85f7b199c707416e3e10e6b9e3f4/src/pk11.c#L278-L288

**Comment by irtimmer** [comment]
Issue have been solved with commit a639761175de20fd4c3c347d0651fee72eddc51f
