### ISSUE TITLE
“No matching objects found” while executing  p11tool --list-privkeys pkcs11:model=TPM2

### ISSUE THREAD

**Issue by leeehui** [irtimmer/tpm2-pk11#55]
I am trying to generate certificate according to [Create certificate](https://github.com/irtimmer/tpm2-pk11/wiki/Create-certificate),  I am using a tpm simulator, the configuration of ~/.tpm2/config is:
```
# Type can be device/socket/tabrmd
type tabrmd
# Hostname to connect when using socket
hostname localhost
# Port number of TPM socket to connect to
port 2321
# Device to use as TPM
device /dev/tpm0
# Sign using encrypt in case TPM doesn't support hash format
# For example SSH use SHA512 which isn't supported by all TPM's
# Enabling this option requires key's to be encryption keys instead of signing only keys
sign-using-encrypt true
certificates ~/.tpm2/certs/
```
my question is how does "p11tool" find the key generated in [Create TPM key](https://github.com/irtimmer/tpm2-pk11/wiki/Create-TPM-key)  ?

thanks.

**Comment by liuqun** [comment]
$ man p11tool
To use PKCS 11 tokens with GnuTLS the p11-kit configuration files need to be setup.  That is create
a .module file in /etc/pkcs11/modules with the contents 'module: /path/to/pkcs11.so'.  Alternatively
the  configuration  file  /etc/gnutls/pkcs11.conf  has to exist and contain a number of lines of the
form 'load=/usr/lib/opensc-pkcs11.so'.

**Comment by liuqun** [comment]
A better sulotion:

    p11tool --provider=libtpm2-pk11.so --list-all "pkcs11:model=TPM2"

**Comment by leeehui** [comment]
thanks, I will try it.

**Comment by SilverJan** [comment]
@liuqun 

> A better solution:
> `p11tool --provider=libtpm2-pk11.so --list-all "pkcs11:model=TPM2"`

With this command the configuration you mentioned before (your comment from 01/03/2018 regarding p11-kit) is not needed anymore?

**Comment by liuqun** [comment]
`p11tool --provider=/path/to/libtpm2-pk11.so` should work. I guess.
@SliverJan ，have a good luck!
