### ISSUE TITLE
tpm2_createprimary: invalid option -- 'H'

### ISSUE THREAD

**Issue by liuqun** [irtimmer/tpm2-pk11#67]
Since https://github.com/tpm2-software/tpm2-tools/commit/53a6e1a6465a5ff77765636423065aac7b472fd0, the development version of tpm2-tools has changeed its command-line options again!
> tpm2_createprimary: -H changes to -a for specifying hierarchy. 

The current code in our Travis-CI test script and our [wiki page](https://github.com/irtimmer/tpm2-pk11/wiki/Create-TPM-key) is outdated.
https://github.com/irtimmer/tpm2-pk11/blob/79e91891f371b40e920aeb484f04f76802337f6e/test/bat/test_util.bash#L2

You will got an error from the newest tpm2_createprimary:
```
$ tpm2_createprimary -H o -g sha256 -G rsa -C po.ctx 
tpm2_createprimary: invalid option -- 'H'
```

**Comment by liuqun** [comment]
Patch code for this issue is upload in f52b74f

**Comment by liuqun** [comment]
Another trouble:
https://github.com/tpm2-software/tpm2-tools/pull/958 Has changed both "tpm2_createprimary -H" and "tpm2_evictcontrol -A"

```
# tpm2_evictcontrol: invalid option -- 'A'
```
bug at https://travis-ci.org/liuqun/tpm2-pk11/jobs/361046777#L2041

**Comment by liuqun** [comment]
3.0.3 should be
```
tpm2_evictcontrol -A o -c obj.ctx -H 0x81010010
tpm2_evictcontrol --auth o -c obj.ctx -H 0x81010010
```

Branch master should be:
```
tpm2_evictcontrol -a o -c obj.ctx -H 0x81010010
tpm2_evictcontrol --hierarchy o -c obj.ctx -H 0x81010010
```

Here, I can't handle both two branch as what I did with tpm2_createprimary in f52b74f 
What should we do?

**Comment by laanwj** [comment]
Also noticed there's a lot of option drift, started out from the instructions on the arch wiki (https://wiki.archlinux.org/index.php/Tpm2-pk11) which are completely wrong when running the version from git.

**Comment by liuqun** [comment]
Fixed by https://github.com/irtimmer/tpm2-pk11/commit/f91690f7d0fb385aec2428befa31de1f3802bfa1
